# Generated by Django 3.0.7 on 2020-06-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='personalBest',
        ),
    ]
