# Generated by Django 3.0.7 on 2020-06-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_userdata_personalbest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('game_counts', models.IntegerField()),
                ('personal_best', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
