# Generated by Django 3.0.7 on 2020-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200611_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodel',
            name='email',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
